# Generated by Django 2.1.5 on 2019-03-09 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date_price', models.DateTimeField()),
            ],
            options={
                'ordering': ('-date_price',),
                'get_latest_by': 'date_price',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DateField()),
                ('record', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
            options={
                'ordering': ('-payment',),
            },
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets', models.DecimalField(decimal_places=2, max_digits=14)),
                ('liabilities', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('operating_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'financial results',
                'ordering': ('-total_revenue',),
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('open', models.DecimalField(decimal_places=2, max_digits=11)),
                ('volume', models.PositiveIntegerField()),
                ('change', models.FloatField()),
                ('percent_change', models.FloatField()),
                ('date_price', models.DateField()),
            ],
            options={
                'ordering': ('-date_price',),
                'get_latest_by': 'date_price',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'stock details',
                'ordering': ('sector',),
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Stocks',
                'verbose_name_plural': 'Stocks',
                'ordering': ('ticker',),
            },
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='stocks.Stocks'),
        ),
        migrations.AddField(
            model_name='prices',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past', to='stocks.Stocks'),
        ),
        migrations.AddField(
            model_name='financial',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='stocks.Stocks'),
        ),
        migrations.AddField(
            model_name='dividends',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='stocks.Stocks'),
        ),
        migrations.AddField(
            model_name='currentprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='stocks.Stocks'),
        ),
    ]
