# Generated by Django 2.1.5 on 2019-02-21 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date_price', models.DateField()),
            ],
            options={
                'ordering': ('-date_price',),
                'get_latest_by': 'date_price',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Stocks',
                'verbose_name_plural': 'Stocks',
                'ordering': ('ticker',),
            },
        ),
        migrations.AddField(
            model_name='prices',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.Stocks'),
        ),
    ]
