# Generated by Django 2.1.5 on 2019-02-28 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date_price', models.DateTimeField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.Stocks')),
            ],
            options={
                'ordering': ('-date_price',),
                'get_latest_by': 'date_price',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PastPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date_price', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_price', to='stocks.Stocks')),
            ],
            options={
                'ordering': ('-date_price',),
                'get_latest_by': 'date_price',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='prices',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
    ]
