# Generated by Django 2.1.5 on 2019-03-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20190228_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastPrices',
            new_name='Prices',
        ),
    ]
