# Generated by Django 2.1.5 on 2019-03-03 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20190303_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_prices', to='stocks.Stocks'),
        ),
    ]
