# Generated by Django 2.1.5 on 2019-03-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20190310_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividends',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='dividends',
            name='payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dividends',
            name='record',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='date_price',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='percent_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
