# Generated by Django 2.1.5 on 2019-03-05 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20190303_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DateField()),
                ('record', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='stocks.Stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets', models.DecimalField(decimal_places=2, max_digits=14)),
                ('liabilities', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('operating_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='stocks.Stocks')),
            ],
            options={
                'verbose_name': 'financial results',
                'ordering': ('-total_revenue',),
            },
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('description', models.CharField(max_length=250)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='stocks.Stocks')),
            ],
            options={
                'verbose_name': 'stock details',
                'ordering': ('sector',),
            },
        ),
        migrations.AlterField(
            model_name='currentprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='stocks.Stocks'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past', to='stocks.Stocks'),
        ),
    ]
