# Generated by Django 2.1.5 on 2019-03-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20190310_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
