# Generated by Django 2.1.5 on 2019-03-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20190310_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='price',
        ),
    ]
