# Generated by Django 2.1.5 on 2019-03-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_remove_prices_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=11),
            preserve_default=False,
        ),
    ]
