# Generated by Django 2.1.5 on 2019-03-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_prices_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentprice',
            name='stock',
        ),
        migrations.DeleteModel(
            name='CurrentPrice',
        ),
    ]
