# Generated by Django 2.1.5 on 2019-06-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20190324_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='industry',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='sector',
            field=models.CharField(max_length=200),
        ),
    ]
