# Generated by Django 2.1.5 on 2019-02-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='name',
        ),
    ]
