# Generated by Django 2.1.5 on 2019-02-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190208_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='profile_pics/'),
        ),
    ]
