# Generated by Django 2.1.5 on 2019-02-21 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sum_number', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_open', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beginning_cash', models.DecimalField(decimal_places=2, max_digits=11)),
                ('current_cash', models.DecimalField(decimal_places=2, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('number', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('S', 'SELL'), ('B', 'BUY')], max_length=4)),
                ('date', models.DateTimeField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='portfolio.Portfolio')),
                ('stocks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.Stocks')),
            ],
        ),
    ]
