# Generated by Django 2.1.5 on 2019-05-31 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190309_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_cash', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=11)),
                ('stock_value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='beginning_cash',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='początkowa gotówka'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='gotówka'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='widoczne?'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL, verbose_name='profil'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('S', 'SELL'), ('B', 'BUY')], max_length=4, verbose_name='rodzaj'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='cena'),
        ),
        migrations.AddField(
            model_name='pastportfolio',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio'),
        ),
    ]
