# Generated by Django 2.1.5 on 2019-02-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190221_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='current_cash',
            new_name='cash',
        ),
    ]
