# Generated by Django 2.1.5 on 2019-07-13 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190531_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastportfolio',
            name='parent',
        ),
        migrations.AddField(
            model_name='pastportfolio',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_portfolio', to='portfolio.Portfolio'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('sell', 'SELL'), ('buy', 'BUY')], max_length=4, verbose_name='rodzaj'),
        ),
    ]
