# Generated by Django 2.1.5 on 2019-07-13 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190714_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastportfolio',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_portfolio', to='portfolio.Portfolio'),
        ),
    ]
