# Generated by Django 2.1.5 on 2019-02-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_pastassets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PastAssets',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date',)},
        ),
    ]
